[package]
name = "ifconfig"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.async-std]
version = "1"
default-features = false

[dependencies.async-std-resolver]
version = "0.20.3"

[dependencies.include-flate]
version = "0.1.3"
default-features = false

[dependencies.tera]
version = "1"
default-features = false

[dependencies.tide]
version = "0.16"
default-features = false
features = [
    "h1-server"
]
